# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: ate.dev/v1alpha1
kind: SandboxConfig
metadata:
  name: microvm
spec:
  sandboxClass: microvm
  pauseImage: registry.k8s.io/pause:3.10.2@sha256:f548e0e8e3dc1896ca956272154dde3314e8cc4fde0a57577ee9fa1c63f5baf4
  assets:
    amd64:
      cloud-hypervisor:
        url: azblob://actor-state/runtime/amd64/448af3d4e59b22c2987f7df94c213ad40fb53a10d437e42b5ee6c4fce7c29ecc/cloud-hypervisor
        sha256: 448af3d4e59b22c2987f7df94c213ad40fb53a10d437e42b5ee6c4fce7c29ecc
      virtiofsd:
        url: azblob://actor-state/runtime/amd64/15b2e72a78cc08a9bd8a6943e89fb69c88cb3cbeb63069efceade835342ac7d4/virtiofsd
        sha256: 15b2e72a78cc08a9bd8a6943e89fb69c88cb3cbeb63069efceade835342ac7d4
      kata-kernel:
        url: azblob://actor-state/runtime/amd64/8e9dbc3a6e4c26adb089d23d31201edebce905c7f3e31aa67b32bdd41df1b86f/vmlinux
        sha256: 8e9dbc3a6e4c26adb089d23d31201edebce905c7f3e31aa67b32bdd41df1b86f
      kata-image:
        url: azblob://actor-state/runtime/amd64/96497f64da1de9c7473fef46c3d29ddd0805d334731cf9d903a21a5b2c33cefb/rootfs.img
        sha256: 96497f64da1de9c7473fef46c3d29ddd0805d334731cf9d903a21a5b2c33cefb